env: "local" # Окружение - local, dev или prod
storage_path: "./storage/storage.db" # файл, в котором будет храниться наша БД
http_server:
  address: "localhost:8082"
  # время на чтение запроса и такое же время на отправку ответа, время на обработку не ограничено
  timeout: 4s
  # время жизни соединения с клиентом
  idle_timeout: 60s
  user: "my_user"
  password: "my_pass"